title: Technical Knowledge Base
description: A collection of technical articles and guides
remote_theme: just-the-docs/just-the-docs

# Build settings
markdown: kramdown

# GitHub Pages specific
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true
